### ISSUE TITLE
Cameron wont run his code for me <:(

### ISSUE THREAD

**Issue by dexterh925** [illegitimate-egg/sieve-of-eratosthenes#1]
IM VERY ANGRY THAT HE WONT SHOW ME HIS SIEVE OF ERESTOTHENES <:(

CAMERON SHOW IT TO ME <:(

<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(<:(

**Comment by dexterh925** [comment]
Give me admin
:(

**Comment by dexterh925** [comment]
Me want code

**Comment by illegitimate-egg** [comment]
Please refer to release v1.0.0
